Rustfmt
ufosc/club-backend pull request #14
Opened 2018-09-29 22:37 UTC by igniscyan

# Fixes

This will allow Travis CI to automatically format code be placed inside of the Github repository. We'll have to set up the second CI repo to get this working, but this is as barebones as the config file can get.

Additionally, the rustfmt config has been edited to remove any of the extra features that comes with using default settings and only formats what we need. I have a feeling we may need to end up adding a bit more, because as of right now it only manages the amount of spaces between lines, spaces and tabs, and other small things. If we want truly uniform code, we'll have to include the bits that manages how code blocks are formatted. 

## Related Issues

- None so far, but Travis CI may need to be tested with the current config settings.

2018-09-30 16:31 UTC, mirdaki requested changes
Hey @igniscyan sorry for the delay. It looks pretty good to me, but there are a couple small things
1. I didn't mention it (my bad), but we need to run rust nightly (so Rocket will compile), so that'll need to be [specified ](https://docs.travis-ci.com/user/languages/rust/#choosing-a-rust-version)
2. The `travis.yml` needs a . in-front of it, so it'll need to be renamed to `.travis.yml`

2018-10-25 21:35 UTC, igniscyan commented
Well, sorry for the delay but those super quick fixes are up now. 

Travis now specifies the nightly build. and the file name has been fixed.

2018-10-26 13:01 UTC, mirdaki approved these changes

2018-10-26 13:02 UTC, merged

2018-10-26 13:02 UTC, mirdaki commented
Lets try this out!

Affects #13